### ISSUE TITLE
Plugins failing to load?

### ISSUE THREAD

**Issue by tjrgg** [xojs/xo#473]
I recently upgraded `xo` to v0.30.0. Everything was working fine with v0.29.1, but it seems that now, `xo` fails due to not being able to load `ava` plugin, even though I can see that the plugin is installed in the `xo` directory under `node_modules`.

I tried solving this by installing `eslint-plugin-ava` locally as a dev dependency for my module. This seems to have worked, but introduced the same problem for the `unicorn` plugin (same error, but for unicorn instead of ava). I didn't see anything in the release notes about this, so I'm assuming there's some kind of problem.

The full error message is below. I censored out the full path to my module and replaced it with `...` which represents its root. I'm using Windows, Node 13.13.0, ESLint 7.0.0.

```Failed to load plugin 'ava' declared in 'BaseConfig » C:\...\node_modules\xo\config\plugins.js': Cannot find module 'eslint-plugin-ava'```

**Comment by tjrgg** [comment]
So, after playing around with XO for a while working on #480, I've come to discover that it seems that XO is only looking for configs and plugins in the the main project `node_modules` directory and not the `node_modules` directory of any dependencies. I'm unsure if this is due to the changes in plugin resolving in ESLint 7 or if it's something else.

**Comment by sindresorhus** [comment]
https://github.com/eslint/eslint/issues/3458

**Comment by fregante** [comment]
Duplicate of https://github.com/xojs/xo/issues/546
