### ISSUE TITLE
Typescript required since eslint-config-xo upgrade to 0.51

### ISSUE THREAD

**Issue by xqqp** [xojs/xo#873]
I'm using `eslint-config-xo` in a project not using typescript. Since the upgrade to 0.51 I get the following error:

```
Oops! Something went wrong! :(

ESLint: 10.1.0

Error: Cannot find module 'typescript'
Require stack:
- /my/project/dir/node_modules/@typescript-eslint/typescript-estree/dist/create-program/getWatchProgramsForProjects.js
- /my/project/dir/node_modules/@typescript-eslint/typescript-estree/dist/clear-caches.js
- /my/project/dir/node_modules/@typescript-eslint/typescript-estree/dist/index.js
- /my/project/dir/node_modules/@typescript-eslint/parser/dist/parser.js
- /my/project/dir/node_modules/@typescript-eslint/parser/dist/index.js
- /my/project/dir/node_modules/@typescript-eslint/eslint-plugin/dist/raw-plugin.js
- /my/project/dir/node_modules/@typescript-eslint/eslint-plugin/dist/index.js
- /my/project/dir/node_modules/typescript-eslint/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1383:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Module._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
    at Module.require (node:internal/modules/cjs/loader:1463:12)
    at require (node:internal/modules/helpers:147:16)
    at Object.<anonymous> (/my/project/dir/node_modules/@typescript-eslint/typescript-estree/dist/create-program/getWatchProgramsForProjects.js:43:25)
    at Module._compile (node:internal/modules/cjs/loader:1706:14)
```

After adding the `typescript` package to the dev dependencies, the error does not appear. So it seems that typescript is now a hard dependency of this linter config. I suggest adding it to the dependencies so typescript gets pulled automatically.

**Comment by sindresorhus** [comment]
Will be fixed when https://github.com/xojs/eslint-config-xo/commit/717184bd4ddcc89f395f9afb0c87f0814e57889e is released.
